### ISSUE TITLE
Unary Minus results in error when used with non-digits

### ISSUE THREAD

**Issue by erikverbeek** [neonxp/MathExecutor#83]
Hi,
I've found a case in which the use of the unary minus results in an error. This happens when there is a numeric value in front of it.

Let me give an example:
```
(new NXP\MathExecutor())->execute("3 -log(4)"); //Fine
(new NXP\MathExecutor())->execute("-log(4)"); //Error

(new NXP\MathExecutor())->execute("3 -(2+5)"); //Fine
(new NXP\MathExecutor())->execute("-(2+5)"); //Error
```

The error that results is `A non-numeric value encountered in MathExecutor.php` which I've traced to `defaultOperators()`.
The "-" character ends up in the $a or $b variable as a separate value instead of being part of a negative digit.

**Comment by phpfui** [comment]
Thanks for the feedback.

Alex or I will look into it.  Unary support was added to the old parser, and we may have missed it in the new parser.

Also, if you want to fix it yourself, please submit a PR.  Happy to accept them!

**Comment by phpfui** [comment]
Digging into this a bit, it turns out to be a Tokenizer issue.  Unary operators are a special case. They are really 0-whatever. So when one is identified, the token tree needs to adjusted to add a zero, then the Calculator does not have to deal with it.  Right now the tokenizer is adding a multiply operator and that is barfing.  But if you remove that, the Calculator does not deal with a unary operator.  Not sure if it should. But the point is a unary operator is a special case, and in the case of parens or functions, the special case is not being dealt with correctly.

I am going to put this in my brain's back burner for a while and it will come up with a solution eventually.

**Comment by phpfui** [comment]
So some offline thinking really paid off.  I figured out the problem is minus take two arguments, but unary minus only takes one, DUH! So the solution was to add a unary minus operator (~) since we need a character in add as an array key.  Then I had to allow for negative exponents, and done! V2.1.7 coming up as soon as tests pass.

**Comment by erikverbeek** [comment]
This has fixed our issues with the unary minus. Thank you for the release.

**Comment by phpfui** [comment]
Good to hear.  Thanks for pointing out the issue.
